import { useState, useEffect } from 'react';
import { Heart, Flame, Droplet, Scale, X, Activity, Ruler } from 'lucide-react';
import { ref, onValue, set, get } from 'firebase/database';
import { db, auth } from './firebase';
import './Progress.css';

export default function Progress() {
  const [weight, setWeight] = useState<number | null>(null);
  const [height, setHeight] = useState<number | null>(null);
  const [water, setWater] = useState<number>(0);
  const [caloriesEaten, setCaloriesEaten] = useState<number>(0);
  const [caloriesBurned, setCaloriesBurned] = useState<number>(0);
  
  // Dynamic metrics collected in Explore
  const [gender, setGender] = useState<string>('male');
  const [activity, setActivity] = useState<string>('moderate');
  const [waist, setWaist] = useState<number | null>(null);
  const [arm, setArm] = useState<number | null>(null);
  const [completedWorkouts, setCompletedWorkouts] = useState<any[]>([]);

  // Custom limits generated by Explore Plan Wizard
  const [waterGoal, setWaterGoal] = useState<number>(3000); // default 3L
  const [calorieGoal, setCalorieGoal] = useState<number>(2500); // default 2500 kcal

  const [activeModal, setActiveModal] = useState<string | null>(null);
  const [inputValue, setInputValue] = useState('');
  const [currentUser, setCurrentUser] = useState<any>(null);

  useEffect(() => {
    const unsubscribeAuth = auth.onAuthStateChanged((user) => {
      setCurrentUser(user);
    });
    return () => unsubscribeAuth();
  }, []);
  
  // Realtime Database logic for body stats
  useEffect(() => {
    if (!currentUser) return;
    const userRef = ref(db, `users/${currentUser.uid}`);
    const unsubscribe = onValue(userRef, (snapshot) => {
      const data = snapshot.val();
      if (data) {
        setWeight(data.weight !== undefined ? data.weight : null);
        setHeight(data.height !== undefined ? data.height : null);
        setWater(data.water || 0);
        setCaloriesEaten(data.caloriesEaten || 0);
        setCaloriesBurned(data.caloriesBurned || 0);
        setWaterGoal(data.waterGoal || 3000);
        setCalorieGoal(data.calorieGoal || 2500);
        setGender(data.gender || 'male');
        setActivity(data.activity || 'moderate');
        setWaist(data.waist !== undefined ? data.waist : null);
        setArm(data.arm !== undefined ? data.arm : null);
        setCompletedWorkouts(data.completedWorkouts || []);
      }
    });
    return () => unsubscribe();
  }, [currentUser]);

  const handleSaveData = async () => {
    if (!inputValue || !currentUser) return;
    const userRef = ref(db, `users/${currentUser.uid}`);
    const snapshot = await get(userRef);
    const data = snapshot.val() || {};

    let updates: any = { ...data };

    if (activeModal === 'weight') {
      updates.weight = parseFloat(inputValue);
    } else if (activeModal === 'water') {
      updates.water = (updates.water || 0) + parseInt(inputValue, 10);
    } else if (activeModal === 'meal') {
      updates.caloriesEaten = (updates.caloriesEaten || 0) + parseInt(inputValue, 10);
    } else if (activeModal === 'exercise') {
      updates.caloriesBurned = (updates.caloriesBurned || 0) + parseInt(inputValue, 10);
    } else if (activeModal === 'waist') {
      updates.waist = parseFloat(inputValue);
    } else if (activeModal === 'arm') {
      updates.arm = parseFloat(inputValue);
    }

    set(userRef, updates).then(() => {
      setActiveModal(null);
      setInputValue('');
    });
  };

  const openModal = (type: string) => {
    setActiveModal(type);
    setInputValue('');
  };

  // Dynamic calculations based on user goals
  const remainingKcal = Math.max(0, calorieGoal - caloriesEaten + caloriesBurned);
  const caloriePercent = Math.min(100, (caloriesEaten / calorieGoal) * 100);
  const waterPercent = Math.min(100, Math.round((water / waterGoal) * 100)) || 0;

  // BMI calculation using updated weight and height from profile
  const userHeightMeters = height ? height / 100 : 1.75;
  const bmi = weight ? (weight / (userHeightMeters * userHeightMeters)).toFixed(1) : '--';

  return (
    <div className="toolbox-container">
      <div className="toolbox-header">
        <h2 style={{ fontSize: '1.25rem', fontWeight: 600 }}>Estatísticas do Corpo</h2>
        <span style={{ color: 'var(--accent-primary)', fontSize: '0.8125rem', fontWeight: 600 }}>100% Personalizado</span>
      </div>

      <div className="widgets-grid">
        {/* Activity Widget */}
        <div className="widget-card">
          <div className="widget-header">
            <div className="widget-title">
              <Heart size={16} color="#ff3b30" fill="#ff3b30" />
              <span>Atividade</span>
            </div>
            <div className="widget-value">
              <Flame size={12} color="var(--text-secondary)" />
              <span style={{color: 'var(--text-secondary)'}}>{caloriesBurned} cal</span>
            </div>
          </div>
          <div className="widget-body">
            <div className="activity-rings">
              <div className="ring ring-outer"></div>
              <div className="ring ring-middle"></div>
              <div className="ring ring-inner"></div>
            </div>
            <button className="widget-btn" onClick={() => openModal('exercise')}>Adicionar Exercício</button>
          </div>
        </div>

        {/* Calorie Tracker Widget */}
        <div className="widget-card">
          <div className="widget-header">
            <div className="widget-title">
              <Flame size={16} color="#ff9500" fill="#ff9500" />
              <span>Rastreador de Calorias</span>
            </div>
            <div className="widget-value">
              <span style={{color: 'var(--text-secondary)'}}>{caloriePercent.toFixed(0)}%</span>
            </div>
          </div>
          <div className="widget-body calorie-body">
            <div className="calorie-stats">
              <div className="stat-col">
                <span className="stat-label">+ INGERIDO</span>
                <span className="stat-number">{caloriesEaten}</span>
              </div>
              <div className="stat-col">
                <span className="stat-label">QUEIMADO</span>
                <span className="stat-number">{caloriesBurned}</span>
              </div>
            </div>
            <button className="widget-btn" onClick={() => openModal('meal')}>Registrar Refeição</button>
          </div>
          <div className="calorie-progress-container">
            <div className="calorie-progress-bar" style={{ background: `linear-gradient(90deg, #ffcc00 0%, #ff3b30 ${caloriePercent}%, rgba(255,255,255,0.1) ${caloriePercent}%)` }}></div>
            <span className="calorie-remaining">Restam {remainingKcal} kcal (Gasto: {calorieGoal} kcal)</span>
          </div>
        </div>

        {/* Water Minder Widget */}
        <div className="widget-card">
          <div className="widget-header">
            <div className="widget-title">
              <Droplet size={16} color="#0a84ff" fill="#0a84ff" />
              <span>Lembrete de Água</span>
            </div>
            <div className="widget-value">
              <Droplet size={12} color="var(--text-secondary)" />
              <span style={{color: 'var(--text-secondary)'}}>{water} / {waterGoal} ml</span>
            </div>
          </div>
          <div className="widget-body">
            <div className="water-ring">
              <span className="water-percent">{waterPercent}%</span>
            </div>
            <button className="widget-btn" onClick={() => openModal('water')}>Registrar Água</button>
          </div>
        </div>

        {/* Weight Tracker Widget */}
        <div className="widget-card">
          <div className="widget-header">
            <div className="widget-title">
              <Scale size={16} color="var(--text-secondary)" />
              <span>Controle de Peso</span>
            </div>
          </div>
          <div className="widget-body weight-body">
            <div>
              <div className="weight-value">{weight !== null ? weight.toFixed(1) : '--'} kg</div>
              <span className="weight-label">SEU IMC: {bmi}</span>
            </div>
            <button className="widget-btn" onClick={() => openModal('weight')}>Atualizar Peso</button>
          </div>
          <div className="weight-scale">
            <div className="scale-gradient"></div>
            <div className="scale-pointer"></div>
          </div>
        </div>

        {/* Dynamic Anthropometric Measurements Widget */}
        <div className="widget-card" style={{ gridColumn: 'span 2' }}>
          <div className="widget-header">
            <div className="widget-title">
              <Ruler size={16} color="var(--accent-primary)" />
              <span>Medidas & Biometria Corporal</span>
            </div>
          </div>
          
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginTop: '0.75rem' }}>
            <div className="glass-panel" style={{ padding: '0.75rem', borderRadius: '12px', display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
              <span style={{ fontSize: '0.6875rem', color: 'var(--text-secondary)', fontWeight: 600, textTransform: 'uppercase' }}>Cintura (cm)</span>
              <span style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                {waist !== null ? `${waist} cm` : '--'}
              </span>
              <button className="widget-btn" style={{ padding: '0.25rem', fontSize: '0.6875rem', marginTop: '0.25rem' }} onClick={() => openModal('waist')}>Atualizar</button>
            </div>

            <div className="glass-panel" style={{ padding: '0.75rem', borderRadius: '12px', display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
              <span style={{ fontSize: '0.6875rem', color: 'var(--text-secondary)', fontWeight: 600, textTransform: 'uppercase' }}>Braço (cm)</span>
              <span style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                {arm !== null ? `${arm} cm` : '--'}
              </span>
              <button className="widget-btn" style={{ padding: '0.25rem', fontSize: '0.6875rem', marginTop: '0.25rem' }} onClick={() => openModal('arm')}>Atualizar</button>
            </div>
          </div>

          <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: 'var(--text-secondary)', marginTop: '0.75rem', borderTop: '1px solid var(--border-color)', paddingTop: '0.5rem' }}>
            <span>Sexo: {gender === 'male' ? 'Masculino' : 'Feminino'}</span>
            <span>Atividade: {activity === 'sedentary' ? 'Baixa' : (activity === 'moderate' ? 'Moderada' : 'Alta')}</span>
          </div>
        </div>

      </div>

      {/* Historico de Treinos Concluidos */}
      <div className="history-section" style={{ marginTop: '2rem' }}>
        <h3 style={{ fontSize: '1.05rem', fontWeight: 600, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Activity size={18} color="var(--accent-primary)" />
          Histórico de Evolução & Treinos
        </h3>
        
        {completedWorkouts.length === 0 ? (
          <div className="glass-panel" style={{ padding: '2rem', borderRadius: '24px', textAlign: 'center', background: 'rgba(255,255,255,0.01)', border: '1px dashed var(--border-color)' }}>
            <span style={{ fontSize: '1.5rem', display: 'block', marginBottom: '0.5rem' }}>🏋️‍♂️</span>
            <p style={{ fontSize: '0.8125rem', color: 'var(--text-secondary)' }}>Nenhum treino concluído ainda. Inicie e conclua um treino para ver seu histórico de progresso aqui!</p>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {completedWorkouts.slice().reverse().map((w, idx) => (
              <div key={idx} className="glass-panel" style={{ padding: '1rem', borderRadius: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: 'rgba(255,255,255,0.02)', border: '1px solid var(--border-color)' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  <div style={{ width: '40px', height: '40px', borderRadius: '12px', background: 'rgba(225,255,0,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Flame size={20} color="var(--accent-primary)" />
                  </div>
                  <div>
                    <h4 style={{ fontSize: '0.875rem', fontWeight: 700, color: '#fff', margin: 0 }}>{w.title}</h4>
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                      {w.exercisesCount} exercícios • {w.duration} min • {w.date}
                    </span>
                  </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <span style={{ fontSize: '0.875rem', fontWeight: 800, color: 'var(--accent-primary)', display: 'block' }}>+{w.xpEarned} XP</span>
                  <span style={{ fontSize: '0.625rem', color: '#ff9500', fontWeight: 700 }}>CONCLUÍDO ✔</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Modal for Data Input */}
      {activeModal && (
        <div className="modal-overlay">
          <div className="modal-content glass-panel">
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem' }}>
              <h3 style={{ fontSize: '1.25rem', fontWeight: 600 }}>
                {activeModal === 'weight' && 'Registrar Peso (kg)'}
                {activeModal === 'water' && 'Registrar Água (ml)'}
                {activeModal === 'meal' && 'Calorias da Refeição (kcal)'}
                {activeModal === 'exercise' && 'Registrar Gasto Calórico (kcal)'}
                {activeModal === 'waist' && 'Circunferência da Cintura (cm)'}
                {activeModal === 'arm' && 'Circunferência do Braço (cm)'}
              </h3>
              <button onClick={() => setActiveModal(null)} style={{ color: 'var(--text-secondary)' }}>
                <X size={24} />
              </button>
            </div>
            <input 
              type="number" 
              className="weight-input"
              placeholder={
                activeModal === 'weight' ? 'ex: 80.5' : 
                (activeModal === 'water' ? 'ex: 350' : 
                (activeModal === 'meal' ? 'ex: 450' : 
                (activeModal === 'exercise' ? 'ex: 300' : 'ex: 85')))
              }
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              autoFocus
            />
            <button className="primary-btn" style={{ width: '100%' }} onClick={handleSaveData}>
              SALVAR PROGRESSO
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
